import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/navbar";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EMØTIØNULL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " overflow-x-hidden w-screen" }>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
